### ISSUE TITLE
error: only uppercase letters allowed in `symbol_code` string

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/substreams-antelope-tokens#5]
- [ ] Failed (soft): eosio_assert_message assertion failure

> stream invalid: rpc error: code = InvalidArgument desc = rpc error: code = InvalidArgument desc = step new irr: handler step new: execute modules: running executor "map_transfers": execute: maps wasm call: block 12587098: module "map_transfers": general wasm execution panicked: wasm execution failed deterministically: panic in the wasm: "only uppercase letters allowed in symbol_code string" at /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/antelope-0.1.5/src/check.rs:19:5

- network: eos
- block number: 12587098
- transaction: https://eos.eosq.eosnation.io/tx/e78123dc1c58c90ca50d12e0c910f8ada39537c797bbe71c6c6668da04a6fc84

**Comment by YaroShkvorets** [comment]
Fails on this action:
```
"action": {
          "account": "eosio.token",
          "name": "transfer",
          "authorization": [{
            "actor": "cryptohongbo",
            "permission": "active"
          }],
          "jsonData": "{\"from\":\"cryptohongbo\",\"to\":\"frgqfysmvlyo\",\"quantity\":\"21364060 \\u0000\\u0000\\u0004EOS\",\"memo\":\"\"}",
          "rawData": "QA+btNFc/UVAfdwS+2XZXVz9RQEAAAAAAAAABEVPUwAA"
        },
```

THis trx:
```
 "id": "e78123dc1c58c90ca50d12e0c910f8ada39537c797bbe71c6c6668da04a6fc84",
      "blockNum": "12587098",
      "blockTime": "2018-08-23T07:19:21Z",
      "producerBlockId": "00c0105ad23a00d96cb268aeb8916c34eca74e41293c451a4fe09536e282b77b",
      "receipt": {
        "status": "TRANSACTIONSTATUS_SOFTFAIL"
      },
```


Instead of iterating through `block.all_transaction_traces()` we should instead always use `block.executed_transaction_traces()` to filter out those failed transactions
